import {
  DownOutlined
} from "@ant-design/icons";
import type { MenuProps } from "antd";
import { Layout as AntdLayout, Menu, Dropdown, Space, message } from "antd";
import Image from "next/image";
import styles from "./index.module.css";
import { useRouter } from "next/router";
import Head from "next/head";
import { PropsWithChildren, useEffect, useState } from "react";
import Link from "next/link";
import { getUserDetail, logout } from "@/apis/user";
import UserForm from "../UserForm";
import { UserType } from "@/types";
const { Header, Content, Sider } = AntdLayout;



const ITEMS: MenuProps["items"] = [
  {
    //icon: React.createElement(icon),
    label: "Book Management",
    key: "book",

    children: [
      { label: "Book List", key: "/book" },
      { label: "Book Add", key: "/book/add" },
    ],
  },
  {
    //icon: React.createElement(icon),
    label: "Borrow Management",
    key: "borrow",

    children: [
      { label: "Borrow List", key: "/borrow" },
      { label: "Borrow Add", key: "/borrow/add" },
    ],
  },
  {
    //icon: React.createElement(icon),
    label: "Category Management",
    key: "category",

    children: [
      { label: "Category List", key: "/category" },
      { label: "Category Add", key: "/category/add" },
    ],
  },
  {
    //icon: React.createElement(icon),
    label: "User Management",
    key: "user",

    children: [
      { label: "User List", key: "/user" },
      { label: "User Add", key: "/user/add" },
    ],
  },
];
const Layout: React.FC<PropsWithChildren> = ({ children }) => {
  const [data, setData] = useState<Partial<UserType>>()
  const [user, setUser] = useState({ info: { nickName: "" }});
  const router = useRouter();
  const handleMenuClick: MenuProps["onClick"]  = ({ key }) => {
    router.push(key);
  };
  const activeMenu = router.pathname;
  
  useEffect(() => {
    if (typeof window !== "undefined") {
      const userStorage = localStorage?.getItem("user") 
      if (userStorage) {
        setUser(JSON.parse(userStorage))
      }
    }
  }, [])
  

  const USER_ITEMS: MenuProps['items'] = [
    {
      // to do at backend
      label: <span onClick={() => {
        
        const user = localStorage.getItem("user")
        if(user){
          const userId = JSON.parse(user).info._id
          router.push(`/user/edit/${userId}`);
        }
        
      }}>User Center</span>,
      key: '0',
    },
    {
      label: <span onClick={async () => {
        await logout();
        message.success("logout success");
        localStorage.removeItem("user");
        router.push('/login');
      }}>Log out
      </span>,
      key: '1',
    }
  ];

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <AntdLayout>
        <Header className={styles.header}>
          <Image
            src="/logo.svg"
            width={30}
            height={30}
            alt="logo"
            className={styles.logo}
          />
          Library Management System
          <span className={styles.user} >
            <Dropdown menu={{ items: USER_ITEMS }}>
              <a onClick={(e) => e.preventDefault()}>
                <Space>
                  {user?.info?.nickName ? user?.info?.nickName: "Username"}
                  <DownOutlined />
                </Space>
              </a>
            </Dropdown>
          </span>
        </Header>
        <AntdLayout className={styles.innerSection}>
          <Sider width={220} style={{ background: "white" }}>
            <Menu
              mode="inline"
              defaultSelectedKeys={["book"]}
              defaultOpenKeys={["/book"]}
              selectedKeys={[activeMenu]}
              style={{ height: "100%", borderRight: 0 }}
              items={ITEMS}
              onClick={handleMenuClick}
            />
          </Sider>
          <AntdLayout className={styles.contentSection}>
            <Content className={styles.content}>
              {children}
            </Content>
          </AntdLayout>
        </AntdLayout>
      </AntdLayout>
    </main>
    </>
  );
};

export default Layout;
